# ~/.config/hypr/hyprlauncher.conf

general {
    grab_focus = true          # force full keyboard focus grab
}

finders {
    default_finder       = desktop   # desktop | math | unicode
    desktop_prefix        =          # empty = no prefix needed for apps
    math_prefix           = =        # type "= 2+2" to calculate
    unicode_prefix        = .        # type ".heart" for unicode search
    font_prefix           = '        # type "'mono" to browse fonts
    desktop_launch_prefix =          # e.g. "uwsm app --" if you use uwsm
    desktop_icons         = true
}

ui {
    window_width  = 600
    window_height = 400
}