general {
    disable_loading_bar = true
    grace = 0
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 0
    color = rgba(17, 17, 17, 1.0)
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(888888aa)
    inner_color = rgba(222222ff)
    font_color = rgba(111111ff)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 10
    check_color = rgba(00ff99ee)
    fail_color = rgba(ff3333ee)
}

label {
    monitor =
    text = $USER
    color = rgba(eeeeeeff)
    font_size = 20
    font_family = sans
    position = 0, 80
    halign = center
    valign = center
}